class Rocket {
    points = [Utils.Vector(15,0),Utils.Vector(-15,-12),Utils.Vector(-15,12)];
    // the points are aligned horizontally, resulting in the rocket to be facing right side
    rotation = 270;
    v = Utils.Vector(0,0);
    a = Utils.Vector(0,0);

    constructor(x,y){
        this.p = Utils.Vector(canvas.width/2, canvas.height/2);
    }

    draw (){
        let points = Utils.rotatePoints(this.points, Math.PI/180 * this.rotation);
        Utils.DrawPoints(this.p, points, ctx, "stroke");
    }
    update (){

        this.a.y *= 1;
        this.a.x *= 1;
        this.v.y *= 0.95;
        this.v.x *= 0.95;


        if(key[38] == true){
            // Thrust forward
            let thrustAcc = Utils.getForceByAngle(this.rotation);
            this.a.x = thrustAcc.x;
            this.a.y = thrustAcc.y;
        }else {
            this.a.x = 0;
            this.a.y = 0;
        }
        if(key[37] == true){
            this.rotation -= 8;
            if(this.rotation < 0){this.rotation += 360}
        }
        if(key[39] == true){
            this.rotation += 8;
            if(this.rotation >= 360){this.rotation -= 360}
        }


        if(this.p.x > canvas.width){this.p.x = 0}
        if(this.p.x < 0){this.p.x = canvas.width}
        if(this.p.y > canvas.height){this.p.y = 0}
        if(this.p.y < 0){this.p.y = canvas.height}
        
        
        

        this.v.x += this.a.x;
        this.v.y += this.a.y;
        this.p.x += this.v.x;
        this.p.y += this.v.y;
    }
}



class Rock {
    p = [];                 // Position Vector
    v = Utils.Vector(0,0);  // Velocity Vector
    points = [];            // Points (autogenerated)

    constructor(game){
        let x,y = 0;
        if(Math.random()>=0.5){
            x = -(Math.random()*100);
        } else {
            x = canvas.width + (Math.random()*100);
        }
        if(Math.random()>=0.5){
            y = -(Math.random()*100);
        } else {
            y = canvas.height + (Math.random()*100);
        }
        this.p = Utils.Vector(x,y);

        
        let r = Math.random()*30+10; // approx. radius

        // Constructing random rock figure
        for(let i = 0; i < 6; i+=0.7){
            let x = Math.sin(i)*r;
            let y = Math.cos(i)*r;
            let a =Math.random();
            x += a*x
            y += a*y
            this.points.push(Utils.Vector(
                x,y
            ));
        }


        // Initial velocity
        let f = Utils.getForceByAngle(Utils.getAngleBetweenPoints(this.p,game.rocket.p));
        console.log(Utils.getAngleBetweenPoints(this.p, Utils.Vector(100,0)));
        this.v.x = f.x;
        this.v.y = f.y;

    }

    update(){
        this.p.x += this.v.x;
        this.p.y += this.v.y;
    }

    draw(){
        Utils.DrawPoints(this.p, this.points, ctx, "stroke");
    }
}

